name: Docker Push

on:
  push:
    branches:
      - main  # 你可以根据需要更改为其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and Push Docker images
        run: |
          # 定义一个镜像列表
          images=(
            "dqzboy/mirror-hub:latest"
            "dqzboy/mirror-gcr:latest"
            "dqzboy/mirror-ghcr:latest"
            "dqzboy/mirror-k8sgcr:latest"
            "dqzboy/mirror-k8sreg:latest"
            "dqzboy/mirror-quay:latest"
            "dqzboy/mirror-mcr:latest"
            "dqzboy/mirror-elastic:latest"
          )

          # 获取 Docker Hub 用户名
          username=${{ secrets.DOCKER_USERNAME }}

          # 循环处理每个镜像
          for image in "${images[@]}"; do
            # 拉取镜像
            docker pull $image

            # 获取镜像名称
            image_name=$(echo $image | cut -d'/' -f2 | cut -d':' -f1)

            # 标记镜像
            docker tag $image $username/$image_name:latest

            # 上传镜像
            docker push $username/$image_name:latest
          done
